<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>Cyclone.Net.Examples.EchoServer</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Cyclone.Net/Cyclone.Net.csproj" />
    <Compile Include="../Shared/EchoSchema.cs" Link="EchoSchema.cs" />
  </ItemGroup>

</Project>
