name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: build
        run: dotnet build Cyclone.Net.sln -c Release

      - name: test
        run: dotnet run --project tests/Cyclone.Net.Tests/Cyclone.Net.Tests.csproj -c Release --no-build
